// Customers Action Types
export const GET_CUSTOMERS_REQUEST = "GET_CUSTOMERS_REQUEST";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILURE = "GET_CUSTOMERS_FAILURE";

export const GET_PENDING_CUSTOMERS_REQUEST = "GET_PENDING_CUSTOMERS_REQUEST";
export const GET_PENDING_CUSTOMERS_SUCCESS = "GET_PENDING_CUSTOMERS_SUCCESS";
export const GET_PENDING_CUSTOMERS_FAILURE = "GET_PENDING_CUSTOMERS_FAILURE";

// Restaurants Action Types
export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAILURE = "GET_RESTAURANTS_FAILURE";

export const GET_PENDING_RESTAURANTS_REQUEST = "GET_PENDING_RESTAURANTS_REQUEST";
export const GET_PENDING_RESTAURANTS_SUCCESS = "GET_PENDING_RESTAURANTS_SUCCESS";
export const GET_PENDING_RESTAURANTS_FAILURE = "GET_PENDING_RESTAURANTS_FAILURE";
// Users Action Types
export const DELETE_CUSTOMER_REQUEST = "DELETE_CUSTOMER_REQUEST";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_FAILURE = "DELETE_CUSTOMER_FAILURE";

export const ARCHIVE_RESTAURANT_REQUEST = "ARCHIVE_RESTAURANT_REQUEST";
export const ARCHIVE_RESTAURANT_SUCCESS = "ARCHIVE_RESTAURANT_SUCCESS";
export const ARCHIVE_RESTAURANT_FAILURE = "ARCHIVE_RESTAURANT_FAILURE";

export const GET_ARCHIVED_RESTAURANTS_REQUEST = "GET_ARCHIVED_RESTAURANTS_REQUEST";
export const GET_ARCHIVED_RESTAURANTS_SUCCESS = "GET_ARCHIVED_RESTAURANTS_SUCCESS";
export const GET_ARCHIVED_RESTAURANTS_FAILURE = "GET_ARCHIVED_RESTAURANTS_FAILURE";
export const UNARCHIVE_RESTAURANT_REQUEST = 'UNARCHIVE_RESTAURANT_REQUEST';
export const UNARCHIVE_RESTAURANT_SUCCESS = 'UNARCHIVE_RESTAURANT_SUCCESS';
export const UNARCHIVE_RESTAURANT_FAILURE = 'UNARCHIVE_RESTAURANT_FAILURE';


